namespace Atlas.Domain.Enums;

public enum IntegrationProvider
{
    GitHub = 1,
    Jira = 2,
    Trello = 11,
    Notion = 12,
    Figma = 20,
    AdobeCc = 21,
    Miro = 22,
    LottieFiles = 23,
    Dribbble = 24,
    Zeplin = 25,
    Aws = 30,
    Azure = 31,
    DockerHub = 32,
    Datadog = 33,
    Slack = 40,
    Discord = 41,
    Sentry = 50,
    SonarQube = 51,
    Perplexity = 52,
    Cloudflare = 60,
    Snyk = 61,
    AwsGuardDuty = 62,
    OnePassword = 63,
    VirusTotal = 64,
    Shodan = 65,
    PagerDuty = 66,
    MetaAds = 70,
    GoogleSearchConsole = 71,
    Mailchimp = 72,
    SocialListening = 73,
    Ga4 = 74,
    StripeMkt = 75,
    HubSpot = 76
}