<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AppSettingsMultiPlatformPackage" Version="1.2.1" />
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
        <PackageReference Include="Hangfire.Core" Version="1.8.23" />
        <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.2" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" Version="2.12.46" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Infrastructure\Atlas.Infrastructure\Atlas.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Infrastructure\Atlas.Persistence\Atlas.Persistence.csproj" />
    </ItemGroup>

   
</Project>
