// <auto-generated />
using System;
using Atlas.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Persistence.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260218100018_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("EmailVerificationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneVerificationCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("PhoneVerificationExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PreferredVerificationChannel")
                        .HasColumnType("integer");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetPasswordCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ResetPasswordExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TelegramLinkCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TelegramLinkCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("\"PhoneNumber\" IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AppUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ThemeColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("#007AFF");

                    b.HasKey("Id");

                    b.HasIndex("Profession")
                        .HasDatabaseName("IX_UserProfiles_Profession");

                    b.ToTable("UserProfiles", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.DesignAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ConvertedSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OriginalSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DesignAssets");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.DesignPalette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("DesignPalettes");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("FocusSessions");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Integrations_Status")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX_Integrations_UserProfileId");

                    b.HasIndex("UserProfileId", "Provider")
                        .HasDatabaseName("IX_Integrations_UserProfileId_Provider");

                    b.HasIndex("UserProfileId", "Provider", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Integrations_UserProfileId_Provider_Name")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Integrations", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.OnboardingAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomValue")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("OnboardingAnswers");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.OnboardingOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecommendedIntegration")
                        .HasColumnType("text");

                    b.Property<string>("RecommendedTemplate")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("OnboardingOptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecommendedIntegration = "GitHub",
                            Text = "Developer"
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecommendedIntegration = "Figma",
                            Text = "Designer"
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecommendedIntegration = "Docker",
                            Text = "DevOps Engineer"
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecommendedIntegration = "Jupyter",
                            Text = "Data Scientist"
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Text = "Cyber Security Specialist"
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecommendedIntegration = "OpenAI",
                            Text = "AI/ML Engineer"
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RecommendedIntegration = "Jira",
                            Text = "Product Manager"
                        },
                        new
                        {
                            Id = new Guid("aaaa0001-0001-0001-0001-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Text = "Other"
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Text = "Improve productivity"
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Text = "Organize my work better"
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111112"),
                            RecommendedIntegration = "Slack",
                            Text = "Collaborate with team"
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111112"),
                            Text = "Automate repetitive tasks"
                        },
                        new
                        {
                            Id = new Guid("aaaa0002-0002-0002-0002-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("11111111-1111-1111-1111-111111111112"),
                            RecommendedIntegration = "Jira",
                            Text = "Track projects and deadlines"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "JavaScript / TypeScript"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "Python"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "C# / .NET"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "Java / Kotlin"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "Go"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "Rust"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "PHP"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "Swift / Objective-C"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("bbbb0001-0001-0001-0001-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222201"),
                            Text = "C / C++"
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-0002-0002-0002-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Text = "VS Code"
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-0002-0002-0002-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Text = "JetBrains IDEs"
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-0002-0002-0002-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222202"),
                            RecommendedIntegration = "GitHub",
                            Text = "GitHub"
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-0002-0002-0002-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222202"),
                            RecommendedIntegration = "GitLab",
                            Text = "GitLab"
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-0002-0002-0002-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222202"),
                            RecommendedIntegration = "Docker",
                            Text = "Docker"
                        },
                        new
                        {
                            Id = new Guid("bbbb0002-0002-0002-0002-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222202"),
                            Text = "Postman"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "React / Next.js"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "Angular"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "Vue.js / Nuxt"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "Node.js / Express"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "Django / Flask"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "Spring Boot"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "Laravel"
                        },
                        new
                        {
                            Id = new Guid("bbbb0003-0003-0003-0003-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("22222222-2222-2222-2222-222222222203"),
                            Text = "React Native / Flutter"
                        },
                        new
                        {
                            Id = new Guid("cccc0001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            RecommendedIntegration = "Figma",
                            Text = "Figma"
                        },
                        new
                        {
                            Id = new Guid("cccc0001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Text = "Adobe XD"
                        },
                        new
                        {
                            Id = new Guid("cccc0001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Text = "Sketch"
                        },
                        new
                        {
                            Id = new Guid("cccc0001-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Text = "Adobe Photoshop"
                        },
                        new
                        {
                            Id = new Guid("cccc0001-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Text = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = new Guid("cccc0001-0001-0001-0001-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Text = "Canva"
                        },
                        new
                        {
                            Id = new Guid("cccc0001-0001-0001-0001-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Text = "Framer"
                        },
                        new
                        {
                            Id = new Guid("cccc0001-0001-0001-0001-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333301"),
                            Text = "Blender (3D)"
                        },
                        new
                        {
                            Id = new Guid("cccc0002-0002-0002-0002-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Text = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("cccc0002-0002-0002-0002-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Text = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("cccc0002-0002-0002-0002-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Text = "Motion Design"
                        },
                        new
                        {
                            Id = new Guid("cccc0002-0002-0002-0002-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Text = "Brand Design"
                        },
                        new
                        {
                            Id = new Guid("cccc0002-0002-0002-0002-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Text = "3D Design"
                        },
                        new
                        {
                            Id = new Guid("cccc0002-0002-0002-0002-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("33333333-3333-3333-3333-333333333302"),
                            Text = "Web Design"
                        },
                        new
                        {
                            Id = new Guid("dddd0001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444401"),
                            RecommendedIntegration = "AWS",
                            Text = "AWS"
                        },
                        new
                        {
                            Id = new Guid("dddd0001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444401"),
                            RecommendedIntegration = "Azure",
                            Text = "Azure"
                        },
                        new
                        {
                            Id = new Guid("dddd0001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444401"),
                            RecommendedIntegration = "GoogleCloud",
                            Text = "Google Cloud"
                        },
                        new
                        {
                            Id = new Guid("dddd0001-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444401"),
                            Text = "DigitalOcean"
                        },
                        new
                        {
                            Id = new Guid("dddd0001-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444401"),
                            Text = "Kubernetes"
                        },
                        new
                        {
                            Id = new Guid("dddd0002-0002-0002-0002-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444402"),
                            RecommendedIntegration = "GitHub",
                            Text = "GitHub Actions"
                        },
                        new
                        {
                            Id = new Guid("dddd0002-0002-0002-0002-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444402"),
                            RecommendedIntegration = "GitLab",
                            Text = "GitLab CI/CD"
                        },
                        new
                        {
                            Id = new Guid("dddd0002-0002-0002-0002-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444402"),
                            Text = "Jenkins"
                        },
                        new
                        {
                            Id = new Guid("dddd0002-0002-0002-0002-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444402"),
                            RecommendedIntegration = "Azure",
                            Text = "Azure DevOps"
                        },
                        new
                        {
                            Id = new Guid("dddd0002-0002-0002-0002-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444402"),
                            Text = "CircleCI"
                        },
                        new
                        {
                            Id = new Guid("dddd0002-0002-0002-0002-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444402"),
                            RecommendedIntegration = "Docker",
                            Text = "Docker"
                        },
                        new
                        {
                            Id = new Guid("dddd0002-0002-0002-0002-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("44444444-4444-4444-4444-444444444402"),
                            Text = "Terraform"
                        },
                        new
                        {
                            Id = new Guid("eeee0001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Text = "Python / Pandas"
                        },
                        new
                        {
                            Id = new Guid("eeee0001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("55555555-5555-5555-5555-555555555501"),
                            RecommendedIntegration = "Jupyter",
                            Text = "Jupyter Notebooks"
                        },
                        new
                        {
                            Id = new Guid("eeee0001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Text = "TensorFlow / PyTorch"
                        },
                        new
                        {
                            Id = new Guid("eeee0001-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Text = "SQL / Databases"
                        },
                        new
                        {
                            Id = new Guid("eeee0001-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Text = "Tableau / Power BI"
                        },
                        new
                        {
                            Id = new Guid("eeee0001-0001-0001-0001-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Text = "Apache Spark"
                        },
                        new
                        {
                            Id = new Guid("eeee0001-0001-0001-0001-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("55555555-5555-5555-5555-555555555501"),
                            Text = "R / RStudio"
                        },
                        new
                        {
                            Id = new Guid("ffff0001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("66666666-6666-6666-6666-666666666601"),
                            Text = "Penetration Testing"
                        },
                        new
                        {
                            Id = new Guid("ffff0001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("66666666-6666-6666-6666-666666666601"),
                            Text = "Network Security"
                        },
                        new
                        {
                            Id = new Guid("ffff0001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("66666666-6666-6666-6666-666666666601"),
                            Text = "Application Security"
                        },
                        new
                        {
                            Id = new Guid("ffff0001-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("66666666-6666-6666-6666-666666666601"),
                            Text = "Cloud Security"
                        },
                        new
                        {
                            Id = new Guid("ffff0001-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("66666666-6666-6666-6666-666666666601"),
                            Text = "Incident Response"
                        },
                        new
                        {
                            Id = new Guid("ffff0001-0001-0001-0001-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("66666666-6666-6666-6666-666666666601"),
                            Text = "Security Operations (SOC)"
                        },
                        new
                        {
                            Id = new Guid("1111a001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("77777777-7777-7777-7777-777777777701"),
                            RecommendedIntegration = "OpenAI",
                            Text = "OpenAI / GPT"
                        },
                        new
                        {
                            Id = new Guid("1111a001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("77777777-7777-7777-7777-777777777701"),
                            Text = "TensorFlow"
                        },
                        new
                        {
                            Id = new Guid("1111a001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("77777777-7777-7777-7777-777777777701"),
                            Text = "PyTorch"
                        },
                        new
                        {
                            Id = new Guid("1111a001-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("77777777-7777-7777-7777-777777777701"),
                            Text = "LangChain"
                        },
                        new
                        {
                            Id = new Guid("1111a001-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("77777777-7777-7777-7777-777777777701"),
                            RecommendedIntegration = "HuggingFace",
                            Text = "Hugging Face"
                        },
                        new
                        {
                            Id = new Guid("1111a001-0001-0001-0001-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("77777777-7777-7777-7777-777777777701"),
                            Text = "Anthropic / Claude"
                        },
                        new
                        {
                            Id = new Guid("1111a001-0001-0001-0001-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("77777777-7777-7777-7777-777777777701"),
                            Text = "Stable Diffusion / DALL-E"
                        },
                        new
                        {
                            Id = new Guid("2222a001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("88888888-8888-8888-8888-888888888801"),
                            RecommendedIntegration = "Jira",
                            Text = "Jira"
                        },
                        new
                        {
                            Id = new Guid("2222a001-0001-0001-0001-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("88888888-8888-8888-8888-888888888801"),
                            Text = "Asana"
                        },
                        new
                        {
                            Id = new Guid("2222a001-0001-0001-0001-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("88888888-8888-8888-8888-888888888801"),
                            RecommendedIntegration = "Trello",
                            Text = "Trello"
                        },
                        new
                        {
                            Id = new Guid("2222a001-0001-0001-0001-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("88888888-8888-8888-8888-888888888801"),
                            Text = "Linear"
                        },
                        new
                        {
                            Id = new Guid("2222a001-0001-0001-0001-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("88888888-8888-8888-8888-888888888801"),
                            RecommendedIntegration = "Notion",
                            Text = "Notion"
                        },
                        new
                        {
                            Id = new Guid("2222a001-0001-0001-0001-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("88888888-8888-8888-8888-888888888801"),
                            RecommendedIntegration = "Confluence",
                            Text = "Confluence"
                        },
                        new
                        {
                            Id = new Guid("2222a001-0001-0001-0001-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("88888888-8888-8888-8888-888888888801"),
                            Text = "Monday.com"
                        },
                        new
                        {
                            Id = new Guid("2222a001-0001-0001-0001-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            QuestionId = new Guid("88888888-8888-8888-8888-888888888801"),
                            RecommendedIntegration = "Slack",
                            Text = "Slack"
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Entities.OnboardingQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMultiSelect")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetProfession")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("OnboardingQuestions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = false,
                            Order = 1,
                            Text = "What is your profession?"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 2,
                            Text = "What are your main goals for using Atlas?"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 3,
                            TargetProfession = 1,
                            Text = "Which programming languages do you primarily work with?"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 4,
                            TargetProfession = 1,
                            Text = "Which development tools do you use?"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 5,
                            TargetProfession = 1,
                            Text = "Which frameworks/libraries are you most experienced with?"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 3,
                            TargetProfession = 2,
                            Text = "Which design tools do you use?"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 4,
                            TargetProfession = 2,
                            Text = "What is your design specialization?"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 3,
                            TargetProfession = 3,
                            Text = "Which cloud platforms do you work with?"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 4,
                            TargetProfession = 3,
                            Text = "Which CI/CD tools do you use?"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 3,
                            TargetProfession = 4,
                            Text = "Which data science tools and libraries do you use?"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666601"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 3,
                            TargetProfession = 5,
                            Text = "What is your security focus area?"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777701"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 3,
                            TargetProfession = 6,
                            Text = "Which AI/ML frameworks do you work with?"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888801"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            IsMultiSelect = true,
                            Order = 3,
                            TargetProfession = 7,
                            Text = "Which project management tools do you use?"
                        });
                });

            modelBuilder.Entity("Atlas.Domain.Entities.PaletteColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DesignPaletteId")
                        .HasColumnType("uuid");

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PaletteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DesignPaletteId");

                    b.ToTable("PaletteColors");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ProjectProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastMigrationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MigrationProjectPath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartupProjectPath")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ProjectProfiles");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Script", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkingDirectory")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Scripts");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Snippet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Snippets");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MetaData")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX_Workspaces_UserProfileId");

                    b.HasIndex("UserProfileId", "IsDefault")
                        .HasDatabaseName("IX_Workspaces_UserProfileId_IsDefault")
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("UserProfileId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Workspaces_UserProfileId_Name")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("Workspaces", "atlas");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.WorkspaceIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("IX_WorkspaceIntegrations_IntegrationId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_WorkspaceIntegrations_WorkspaceId");

                    b.HasIndex("WorkspaceId", "IntegrationId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkspaceIntegrations_WorkspaceId_IntegrationId")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("WorkspaceIntegrations", "atlas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Integration", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AppUserProfile", null)
                        .WithMany("Integrations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.OnboardingOption", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.OnboardingQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.PaletteColor", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.DesignPalette", null)
                        .WithMany("Colors")
                        .HasForeignKey("DesignPaletteId");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AppUserProfile", null)
                        .WithMany("Workspaces")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.WorkspaceIntegration", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Workspace", "Workspace")
                        .WithMany("WorkspaceIntegrations")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AppUserProfile", b =>
                {
                    b.Navigation("Integrations");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.DesignPalette", b =>
                {
                    b.Navigation("Colors");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.OnboardingQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("WorkspaceIntegrations");
                });
#pragma warning restore 612, 618
        }
    }
}
